### ISSUE TITLE
vericoin bootstrap fails to download on MacOS

### ISSUE THREAD

**Issue by ToxiKejtor** [vericoin/vericoin#16]
When going file > reload blockchain, download from https://cdn.vericonomy.com/bootstrap.zip always fail after couple seconds.
It happens on my current Macbook Pro M1, but on previous Macbook Intel happened as well. In result, syncying wallet takes enormous amount of time.

After looking closer into this, it seems that trying to manually download bootstrap via Chrome fails couple seconds in as well. But surprisingly downloading it via Safari works fine.

![Screenshot 2021-06-15 at 11 00 37](https://user-images.githubusercontent.com/22470921/122024651-eab7cf00-cdc8-11eb-9340-14cb13d91fed.png)

**Comment by mderasse** [comment]
Hi,

A new version will be released soon and a beta will be shared this week. 

I will look into the webserver also as it's not normal that it fail  in chrome.

**Comment by mderasse** [comment]
I didn't a few change on the webserver that should avoid the downloading issue.

Meanwhile we just released a new beta version for Vericoin:
**Linux**: https://files.vericonomy.com/vrc/2.0/releases/2.0.0.3/Vericoin_Wallet-2.0.0.3-Linux-x64.AppImage
**MacOs**: https://files.vericonomy.com/vrc/2.0/releases/2.0.0.3/Vericoin_Wallet-2.0.0.3-MacOs-x64.dmg
**Windows**: https://files.vericonomy.com/vrc/2.0/releases/2.0.0.3/vericoin-2.0.0.3-win64-setup-unsigned.exe
